//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Final_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int SN { get; set; }

        [Display(Name = "名稱")]
        public string Title { get; set; }

        [Display(Name = "分類")]
        public string Category { get; set; }

        [Display(Name = "價錢")]
        public int Money { get; set; }

        [Display(Name = "日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
    }
}
